services:
  db:
    container_name: better_timer_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: better_timer_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  backend:
    container_name: better_timer_backend
    build: ./backend
    restart: on-failure
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
    depends_on:
      - db